spring.application.name=smartworks-api

# Puedes sobreescribir estas variables desde VS Code si quieres.
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/smartworks?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
